#!/bin/sh                                                                                                           

thisdir=$(dirname $(readlink -f $0))
#echo $thisdir                                                                                                      

cd ~/bin
target=./cantora

if [  -L $target ]; then rm $target; fi

ln -vs $thisdir/cantora $target ]))